### ISSUE TITLE
OnUserJoinedBattle(): Lobby server inconsistency

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#442]
Alert dialog box: "OnUserJoinedBattle(): Lobby server inconsistency: user in battle which doesnt exist. Please report as lobby server bug."

Clicking OK will just spawn a new dialog box

Happens at springlobby launch.

**Comment by Ruwetuin** [comment]
just saw on irc someone else had the same issue.

Also after a lot of OK  clicks, the dialogs dissapeared, but after about 30 secs the lobby crashed anyway,

**Comment by Bla1** [comment]
I have this issue too

**Comment by jamerlan** [comment]
+1. I had that message yesterday. In the morning it was OK but in the evening it appears again. Sad that lobby crashes

**Comment by ashdnazg** [comment]
Here as well, can't run lobby.

**Comment by LOeT-Zinn** [comment]
**+1**

201 did work for me until today. Then it would not let me join battles anymore (in a very strange way: I did not do really join, did get no messages from joining, yet I did see the stream of ongoing messages just as if I had joined. /part did tell me I am not joined at all, while the messages did go on).
I once did roll back to 201 because 217 did not let me connect at all. Now I am with 219 and got this issues here.

(Tip for those affected: Use `[ESC]` to close a focused modal dialog like this one.)

**Comment by LOeT-Zinn** [comment]
If the message box is right, this is the place to go: https://github.com/spring/uberserver/issues/173

**Comment by Ruwetuin** [comment]
I did a rehost on all the blackholehosts since it kept keeping all players in them somehow. i saw myself in multiple host at the same time....

**Comment by abma** [comment]
yes, this is indeed a lobby server bug.thanks a lot for reporting, i've removed the popup as its not useful for most users!
