### ISSUE TITLE
Change wxWidgets to Qt?

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#470]
This is sounds like some kind of BDSM but porting SpringLobby to Qt may give some benefits:
- Qt is mature tooklit, very good quality, no stupid issues dangled untouched for years *
- Qt contains a lot of stuff, so no boost and libalure, wiil be needed => less dependencies
- Qt looks and works great on all platfroms
- Qt libs could be built static, so still single EXE file for Windows users

But there will be a lot of work. It could take some time... This is just a thoughts, I do not insist on it. Who thinks what about it?

*:
http://trac.wxwidgets.org/ticket/3195
https://forums.wxwidgets.org/viewtopic.php?t=22509&p=96571
annoying flickering
and more...

**Comment by abma** [comment]
thats imo a waste of time. before porting springlobby to qt you/we should spent all time into getting an ingame lobby into spring.

also when looking back, most bugs where because of badly written code in springlobby, not wxWidgets.

wxWidgets follows a different approach than qt: it tries to use and look native ui widgets when qt tries to look the same on every platform.

biggest issue with springlobby is, that its far away from beeing written MVC, so it would be a lot of work. many logic is still in the UI. I'm pretty sure the flickering is because of some bug in our custom implemention of wxListCtrl, even if not, the flickering could be heavily reduced when the logic of updating it is improved.

**Comment by abma** [comment]
imo:

- make springlobby MVC
- test if wxTreeCtrl can be used to replace the lists and drop the custom wxListCtrl.
- use XRC: http://docs.wxwidgets.org/trunk/overview_xrcformat.html

also there is an abandonned lobby written in qt: https://github.com/tizbac/qtlobby

**Comment by abma** [comment]
to fix flickering: write a small test app which automaticly updates a our custom listctrl with a timer.

on linux it doesn't flicker.

**Comment by abma** [comment]
> Qt contains a lot of stuff, so no boost and libalure, wiil be needed => less dependencies

only libalure could be dropped. on windows libalure isn't required. libboost is only used for small stuff, it could be replaced by wxWidgets stuff or maybe already c++11 stuff, but is used to make liblsl useable for other projects.

**Comment by Usaga** [comment]
Good arguments))))) Probably polish current code is much better solution...

**Comment by Usaga** [comment]
What is ingame lobby? It is about to move lobby functionality into the spring engine?

**Comment by abma** [comment]
https://springrts.com/phpbb/viewtopic.php?f=64&t=32030

**Comment by abma** [comment]
>  polish current code

fully agreed :)
