### ISSUE TITLE
Static build of SpringLobby

### ISSUE THREAD

**Issue by Usaga** [springlobby/springlobby#474]
Spring engine is available in static build for linux making it very easy to install and run. Almost like under Windows. Looks like users very like it. Could it be possible to make SpringLobby build static so it will be indifferent for system libs upgrade/version change or just put static version on springlobby.info?
I think this will be very convenient for users to install and update SL.

**Comment by abma** [comment]
when doing this imo springs and springlobbys buildbots have to be merged because the used libs/libstdc++ have to be the same.

or better: implement #43

**Comment by JoshuaPettus** [comment]
interestingly with OSX, this is a non-issue, as whether libraries are static or dynamically linked, they can still be portable in the app structure.

**Comment by abma** [comment]
> libs/libstdc++ have to be the same.

sadly that is an issue on osx.

**Comment by JoshuaPettus** [comment]
true, but they can be included in the app.

**Comment by Usaga** [comment]
I do not understand, why spring and springlobby must have the same libstdc++?

**Comment by Usaga** [comment]
...And distinguishing SpringLobby from unitsync library does not intersects with proposal of static building of application. Or I missed something?

**Comment by abma** [comment]
https://springrts.com/phpbb/viewtopic.php?f=65&t=32856

springlobby loads unitsync and when compiled with different boost/libstdc++ you get weird crashes / memory corruption / ...

-> same build env has to be used for unitsync + springlobby.

**Comment by Usaga** [comment]
I still do not get it. Statically linked spring works fine with dynamically linked SpringLobby. So, it looks like all library versions is in sync or absolutely compatible?

**Comment by abma** [comment]
> Statically linked spring works fine with dynamically linked SpringLobby

not true on osx with different libstdc++ / compiler used for spring and springlobby.

**Comment by abma** [comment]
you get errors like "pointer being freed was not allocated"

**Comment by Usaga** [comment]
Oh, I didn't know that

**Comment by abma** [comment]
in https://springrts.com/phpbb/viewtopic.php?f=65&t=32856 a springlobby .app for osx was created, idk if this specific error was solved or not.

imo this thread here is more about a linux static build of springlobby?!

**Comment by Usaga** [comment]
When I created this thread I didn't know there is difference in linux builds and osx builds...

But in case of linux is it possible to do this?

**Comment by abma** [comment]
it should. but i never tried to static link with wxwidgets, other libs should work without problems.

**Comment by JoshuaPettus** [comment]
I've been putting out springlobby and spring OSX apps for a while now. 
https://springrts.com/phpbb/viewtopic.php?f=65&t=32970
I have been building springlobby with clang, because it works, and have no errors in compiling. And
Spring . app (with unitsync) with gcc4.9, because clang doesn't work there.  I haven't noticed any crashes when loading unitsync.  In fact, springlobby tends to be more stable then spring itself. ( Not often, but occasionally spring.app will quit out with a segfault. )   As I said, the point remains,  dynamically linked or statically linked in an app bundle doesn't matter.  It is all a self contained environment.  If an app was built against gcc, then dylibbundler, which I use to bundle the apps, uses apple's otool to see that the executable was linked against libstdc++ and include it as well with all other dependencies (and their dependencies and so forth).

**Comment by abma** [comment]
https://github.com/nsg/snap-springlobby
