### ISSUE TITLE
Lobby Lag

### ISSUE THREAD

**Issue by logit05** [springlobby/springlobby#618]
On lobby start, after a game finishes, or after map download complete I get 30s of lobby lag to where it's non responsive.

Each time it happens in offical server chat I get,
"[16:37:06] ** Server ** Springlobby hung or stale clock. Got no timer for 38207 msec
[16:44:23] ** Server ** Springlobby hung or stale clock. Got no timer for 39543 msec
[17:28:37] ** Server ** Springlobby hung or stale clock. Got no timer for 39083 msec
[17:57:13] ** Server ** Springlobby hung or stale clock. Got no timer for 39098 msec"

**Comment by abma** [comment]
indexing games/maps/demos takes to long. do you have several .sdd archives in the data dirs of spring?

also you can try to delete demos files, this should speed it up.

this problem should be slightly improved in the next version of springlobby and heavily improve with the next release of spring.

**Comment by logit05** [comment]
Moving my demos to clean out the folder seems to have fixed it, Thank you

**Comment by abma** [comment]
ok, thx.

this can/should be fixed in springlobby. problem is, that loading of replays blocks other calls to unitsync:

https://github.com/springlobby/lsl/blob/5d3954a5d70d2383a8845f4adcb898334b09e127/src/lslunitsync/unitsync.cpp#L770

-> could be fixed by first fetching the data dir and then unlock unitsync. then list/load all demofiles (without blocking unitsync any more)
