### ISSUE TITLE
[linux][SpringLobby 0.243-105-g8f63258 (unix x64)] download develop engine crashes client

### ISSUE THREAD

**Issue by TurBoss** [springlobby/springlobby#624]
when I try to download a develop engine ie from my autohost setup
the client crashes

here is the terminal log
http://paste.springfiles.com/view/c3b8cb28
thx

**Comment by TurBoss** [comment]
remove the new downloaded engine solves the issue

**Comment by abma** [comment]
whats the output of

   ldd /home/jauria/.spring/engine/100.0.1-931-g3be35a2 develop/libunitsync.so

?

**Comment by abma** [comment]
hm, seems i can reproduce it:

http://paste.springfiles.com/view/raw/67c8cc44

possible related to https://springrts.com/phpbb/viewtopic.php?f=64&t=28000&start=20#p574915

"I rebuilt flobby with boost 1.60 today and it seems the C++ ABI change caused a crash in the downloaded 100.0 libunitsync.so."

**Comment by TurBoss** [comment]
too late but here is it
http://paste.springfiles.com/view/c3498ed4

**Comment by abma** [comment]
did you compile springlobby yourself?

if so, which compiler version did you use?

**Comment by TurBoss** [comment]
yes is the latest from github
with all submodules updated

**Comment by abma** [comment]
which compiler version did you use? 5.x?

**Comment by abma** [comment]
ok, the problem is that the static builds of spring and unitsync which is used by springlobby is compiled with with gcc 4.x. 

gcc 5 introduces an new abi in libstdc++ which makes the executable incompatbile to unitsync.

so only workarround for this is to compile unitsync and springlobby with a compiler which uses the same libstdc++ abi.

but: you can't just switch your local compiler to 4.x when wxwidgets / boost was compiled with 5.x. you have to recompile all c++ libs with the same compiler it seems.

:-(

#48 contains some possible solutions

this partly implements a metadata extractor + todo list: https://github.com/springlobby/lsl/issues/4

**Comment by abma** [comment]
hmm, i've investigated this problem a bit more, seems its related to boost::filesystem only.

in my test-version here it seems to work, when i remove boost::filesystem which is used in only very few places in springlobby.

so removal of boost::filesystem possible fixes this!

**Comment by abma** [comment]
@TurBoss does it work for you again with the most recent version?

**Comment by TurBoss** [comment]
worked fine thank you
