### ISSUE TITLE
russian text is not appearing in battleroom log

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#639]
latest springlobby - can't send russian text in battleroom
I can type a message in russian but when I press "Enter" - it not appended to battleroom log

commit 606db6210cfa489b8bb96d346ee463ae673a4d40
Author: abma <spring@abma.de>
Date:   Tue Feb 23 00:54:55 2016 +0100

**Comment by Usaga** [comment]
Yep, it is really broken - I can see text I tayped but it in wrong encoding.

**Comment by abma** [comment]
wtf?

** (springlobby:3954): WARNING **: Error converting text from IM to UTF-8: Invalid byte sequence in conversion input

**Comment by abma** [comment]
i get this error with a fresh compiled springlobby 0.243 with empty config, too.

some system lib was updated?!

@jamerlan which linux distribution + version are you using?

**Comment by abma** [comment]
i get this error in _every_ input field!

gdb springlobby
break g_log
(gdb) bt
0  0x00007ffff2462980 in g_log () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
1  0x00007fffdda114cd in ?? () from /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-xim.so
2  0x00007fffdda123c7 in ?? () from /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-xim.so
3  0x00007ffff071be03 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
4  0x00007ffff06c7e8c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
5  0x00007ffff0732e5c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
6  0x00007ffff6a1e015 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
7  0x00007ffff6a3060e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
8  0x00007ffff6a38899 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
9  0x00007ffff6a3912f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
10 0x00007ffff084acdc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
11 0x00007ffff085e79d in gtk_window_propagate_key_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
12 0x00007ffff5068ce8 in ?? () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
13 0x00007ffff0732e5c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
14 0x00007ffff6a1e015 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
15 0x00007ffff6a30061 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
16 0x00007ffff6a38899 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
17 0x00007ffff6a3912f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
18 0x00007ffff084acdc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
19 0x00007ffff07316d7 in gtk_propagate_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
20 0x00007ffff07319ab in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
21 0x00007ffff03a5c1c in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
22 0x00007ffff245bff7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
23 0x00007ffff245c250 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
24 0x00007ffff245c572 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
25 0x00007ffff0730a07 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
26 0x00007ffff5049055 in wxGUIEventLoop::DoRun() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
27 0x00007ffff49f22b3 in wxEventLoopBase::Run() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
28 0x00007ffff49b7746 in wxAppConsoleBase::MainLoop() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
29 0x00007ffff4a43e80 in wxEntry(int&, wchar_t**) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
30 0x000000000084d9f2 in main (argc=2, argv=0x7fffffffe448) at src/springlobbyapp.cpp:70


dpkg -S /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-xim.so
libgtk2.0-0:amd64: /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-xim.so

-> the error message is caused by libgtk2.

from /var/log/dpkg.log

2016-02-16 23:23:51 upgrade libgtk2.0-0:amd64 2.24.28-1ubuntu1 2.24.28-1ubuntu1.1

so, it was recently updated here, can other affected persons confirm this?

**Comment by abma** [comment]
deleting po/*.gmo + /usr/local/share/locale/*/LC_MESSAGES/springlobby.mo and regenerating these fixed it for me.

i guess something in the format of the translation files has changed.

**Comment by jamerlan** [comment]
I don't know why you closed this issue :( not fixed! I re-downloaded sources and re-compiled - still not fixed.
I created video for you: https://youtu.be/dMI2TcFt1vA
BTW: I was [teh]decay but when I send message to other person (FALSCAN or Flow) - it displayed like other person said my text.

**Comment by abma** [comment]
because its not a springlobby issue. its caused by old files laying arround in your system.

i.e. deleting /usr/local/share/locale fixes it.

**Comment by abma** [comment]
err: it seems to be caused by missconfigured input system...

**Comment by abma** [comment]
in other words: the same problem exists with an older version of springlobby

**Comment by jamerlan** [comment]
I downgraded springlobby to 5a3d161 and it works :-) latest commits have bugs

**Comment by abma** [comment]
oO

now i'm totally confused about this. sorry, its a really weird bug...

**Comment by abma** [comment]
i know this info is redundant:

the sending part is broken, converting from keypresses to utf8 fails on windows

**Comment by abma** [comment]
sorry for the confusion, there were 3 bugs:

1. i couldn't type special chars on linux and got this error in console:
** (springlobby:3954): WARNING **: Error converting text from IM to UTF-8: Invalid byte sequence in conversion input
2. sender name was shown as receiver
3. special chars broken when sending

should be all fixed now! thanks for reporting!
