### ISSUE TITLE
downloading maps crashes SL

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#897]
first happened to me this evening, after being away for a few days - several other users said they have the same issue and blamed it on the recent server "update", some seemed to think it affected all windows users

downloading a new map results in 
![untitled](https://user-images.githubusercontent.com/3885930/48319001-d8b59480-e5ff-11e8-807a-19188ff70590.png)
followed by
![untitled2](https://user-images.githubusercontent.com/3885930/48319003-dd7a4880-e5ff-11e8-8bef-b1f710ebe2fa.png)
(often with many more popups), then SL appears to crash/hang and closes itself shortly after. 

[springlobby.log](https://github.com/springlobby/springlobby/files/2569967/springlobby.log)

**Comment by abma** [comment]
caused by https://springrts.com/phpbb/viewtopic.php?f=71&t=38494
dns entry for https://spring1.admin-box.com/ is wrong.

regardingless of that: it shouldn't crash / use the other mirror which is available for download.

i've manually disabled the broken mirror on springfiles for now.

thanks for reporting!

**Comment by abma** [comment]
A LOT stuff changed in pr-downloader / springlobby, i assume this specific crash / bug is fixed or at least behaves differently.
